baseURL = "https://elarkasi.github.io"
languageCode = "zh-cn"
title = "凭风欲上九重楼"
theme = "m10c"
paginate = 10
enableEmoji = true
disqusShortname = "elarkasi-blog"

[params]
 author = "九重楼"
 description = "elarkasi"
 [[params.social]]
   name = "github"
   url = "https://github.com/elarkasi"
 [[params.social]]
   name = "instagram"
   url = "https://instagram.com/elarkasi"

# Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  [params.style]
    darkestColor = "#315659"
    darkColor = "#253031"
    primaryColor = "#dad865"
    lightColor = "#96a879"
    lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
